server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 0609

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

